pull_request_rules:
  - name: Label Scala Steward PRs as dependency-update
    conditions:
      - title~=Update .* to .*
    actions:
      label:
        add: [dependency-update]
  - name: Merge Scala Steward PRs on CI success
    conditions:
      - label=dependency-update
      - status-success~=Build and Test
    actions:
      merge:
        method: rebase
        strict: true