addSbtPlugin("com.codecommit"            % "sbt-github-actions" % "0.12.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"       % "2.4.4")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"       % "0.9.32")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"       % "0.1.20")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"        % "0.6.0")
